config/routes.rb
Rails.application.routes.draw do

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }

  devise_for :users
  get 'home/index'
  root to: "home#index"

  resources :technologies

  # https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def index
    @technologies = Technology.all
  end

  def show
    @technology = Technology.find(params[:id])
  end

  def new
  end

  def create
    @technology = Technology.new(technology_params)

    if @technology.valid?
      @technology.save

      redirect_to @technology
    else
      render action 'new'
    end
  end

  def edit
    @technology = Technology.find(params[:id])
  end

  def update
    @technology = Technology.find(params[:id])

    if @technology.update(technology_params)
      redirect_to @technology
    else
      render action 'edit'
    end
  end

  def destroy
    @technology = Technology.find(params[:id])
    @technology.destroy

    redirect_to technologies_path
  end

  private
  def technology_params
    params.require(:technology).permit(:title, :purpose, :description, :doc, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/contacts/create.html.erb
<div class="container mt-5 mb-5">
  <h1>Thanks</h1>
  <small class="text-muted">
    We always glad contact with our readers!
  </small>
</div>

app/views/contacts/new.html.erb
<div class="container mt-5 mb-5">
<h1 class="mb-3">
Contact us
</h1>

<div>
  <%= form_for :contact, url: contacts_path do |f| %>

    <% if @contact && @contact.errors.any? %>
    <div class="border rounded border-danger p-3 col-md-8 mb-3">
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="border rounded p-5 text-muted col-md-8 mb-3">
      <h4>
        <%= f.label :email, class: 'form-group' %>
      </h4>
      <%= f.text_field :email, class: 'form-control', autofocus: true %>
      <div class="invalid-feedback">
        Please add email
      </div>
    </div>

    <div class="border rounded p-5 text-muted col-md-8 mb-3">
      <h3>
        <%= f.label :message, class: 'form-group' %>
      </h3>
      <%= f.text_area :message, class: 'form-control', rows: '5' %>
      <div class="invalid-feedback">
        Please add message
      </div>
    </div>

    <div>
      <%= f.submit 'Send message', class: 'btn btn-primary btn-large' %>
    </div>
  <% end %>
</div>
</div>

app/views/home/index.html.erb
<div class="container mt-5 mb-3">
  <h1>Delper</h1>
  <p class="text-muted">
    Developer helper
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delper4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand" href="/">Delper</a>

      <form class="form-inline my-2 my-lg-0 mr-5">
        <input class="form-control-sm mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 btn-sm" type="submit">Find</button>
      </form>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Contacts', new_contacts_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Terms', terms_path, class: 'nav-link mr-5' %>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Technologies
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">All technologies</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
        </ul>
      </div>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown pr-2">
          <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>

              <div class="dropdown-divider"></div>

              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "dropdown-item text-decoration-none" %>
          <% else %>
              <%= link_to "Sign in", new_user_session_path, :class => "nav-link text-decoration-none" %>
            </div>
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item active">
            <a class="nav-link" href="#" tabindex="-1" aria-disabled="false">Add technology</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Add lesson</a>
          </li>
        <% end %>
      </ul>

    </nav>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-5 mb-5">
  <h1>
    About us
  </h1>

  <small class="text-muted">
    Here you can read about us
  </small>
</div>

app/views/pages/terms.html.erb
<div class="container mt-5 mb-5">
  <h1>
    Terms of service
  </h1>

  <small class="text-muted">
    How you can work with us
  </small>
</div>

app/views/technologies/create.html.erb
<div class="container mt-5 mb-5">
  <h1>Thanks, technology has been created!</h1>

  <%= link_to 'Show all technologies', technologies_path, class: 'text-decoration-none' %>
</div>

app/views/technologies/edit.html.erb
<div class="container mt-5 mb-5">
  <h1 class="mb-5">
    Edit technology
  </h1>

  <div>
    <%= form_for :technology, url: technology_path(@technology), method: :put do |f| %>
      <div class="border rounded p-5 text-muted col-md-8 mb-3">
        <h4>
          <%= f.label :title, class: 'form-group' %>
        </h4>
        <%= f.text_field :title, class: 'form-control', autofocus: true %>
      </div>

      <div class="border rounded p-5 text-muted col-md-8 mb-3">
        <h3>
          <%= f.label :purpose, class: 'form-group' %>
        </h3>
        <%= f.text_field :purpose, class: 'form-control' %>
      </div>

      <div class="border rounded p-5 text-muted col-md-8 mb-3">
        <h3>
          <%= f.label :description, class: 'form-group' %>
        </h3>
        <%= f.text_area :description, class: 'form-control', rows: '5' %>
      </div>

      <div class="border rounded p-5 text-muted col-md-8 mb-3">
        <h3>
          <%= f.label :doc, class: 'form-group' %>
        </h3>
        <%= f.text_field :doc, class: 'form-control' %>
      </div>

      <div class="border rounded p-5 text-muted col-md-8 mb-3">
        <h3>
          <%= f.label :rating, class: 'form-group' %>
        </h3>
        <%= f.text_field :rating, class: 'form-control' %>
      </div>

      <div>
        <%= f.submit class: 'btn btn-primary btn-large' %>
      </div>
    <% end %>
  </div>
</div>

app/views/technologies/index.html.erb
<div class="container mt-5 mb-5">
  <h1 class="mb-5">
    Technologies
  </h1>

  <% @technologies.each do |technology| %>
    <div class="border rounded p-3 mb-5">

      <h2>
        <%= technology.title %>
      </h2>



      <div class="border rounded p-3 mb-3 mt-3">
        <small class="text-muted">
          Purpose
        </small>
        
        <p>
          <%= technology.purpose %>
        </p>
      </div>

      <div class="border rounded p-3 mb-3 mt-3">

        <small class="text-muted">
          Technology description
        </small>

        <p>
          <%= technology.description %>
        </p>
      </div>

      <small class="text-muted">
        Technology doc link
      </small>

      <div class="border rounded p-3 mb-3 mt-3">
        <%= technology.doc %>
      </div>

      <small class="text-muted">
        Technology global rating
      </small>

      <div class="border rounded p-3 mb-4 col-md-2 mt-3">
        <%= technology.rating %>
      </div>

      <div class="container pl-0">
        <%= link_to 'Create', new_technology_path(technology), class: 'btn btn-primary btn-sm mr-1 ml-0' %>
        <%= link_to 'Show', technology_path(technology), class: 'btn btn-primary btn-sm m-1' %>
        <%= link_to 'Edit', edit_technology_path(technology), class: 'btn btn-primary btn-sm m-1' %>
        <%= link_to 'Delete', technology_path(technology), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm m-1' %>
      </div>
    </div>
  <% end %>

</div>

app/views/technologies/new.html.erb
<div class="container mt-5 mb-5">
  <h1 class="mb-5">
    New technology
  </h1>

  <div class="border rounded p-3">
    <%= form_for :technology, url: technologies_path do |f| %>
      <div class="border rounded p-5 text-muted mb-3">
        <h6>
          <%= f.label :title, class: 'form-group' %>
        </h6>
        <%= f.text_field :title, class: 'form-control', autofocus: true %>
      </div>

      <div class="border rounded p-5 text-muted mb-3">
        <h6>
          <%= f.label :purpose, class: 'form-group' %>
        </h6>
        <%= f.text_field :purpose, class: 'form-control' %>
      </div>

      <div class="border rounded p-5 text-muted mb-3">
        <h6>
          <%= f.label :description, class: 'form-group' %>
        </h6>
        <%= f.text_area :description, class: 'form-control', rows: '5' %>
      </div>

      <div class="border rounded p-5 text-muted mb-3">
        <h6>
          <%= f.label :doc, class: 'form-group' %>
        </h6>
        <%= f.text_field :doc, class: 'form-control' %>
      </div>

      <div class="border rounded p-5 text-muted mb-3">
        <h6>
          <%= f.label :rating, class: 'form-group' %>
        </h6>
        <%= f.text_field :rating, class: 'form-control' %>
      </div>

      <div>
        <%= f.submit class: 'btn btn-primary btn-large' %>
      </div>
    <% end %>
  </div>
</div>

app/views/technologies/show.html.erb
<div class="container mt-5 mb-5">

  <h1 class="mt-5 mb-3">
    <%= @technology.title %>
  </h1>

  <small class="text-muted">
    Lesson id: <%= @technology.id %>
  </small>

  <p>
    Technology purpose: <%= @technology.purpose %>
  </p>

  <div class="border rounded p-3 text-muted col-md-8 mb-3">
    <small class="text-muted">
      Technology description: <%= @technology.description %>
    </small>
  </div>

  <div class="border rounded p-3 text-muted col-md-8 mb-3">
    <small>
      Technology docs: <%= @technology.doc %>
    </small>
  </div>

  <div class="border rounded p-3 col-md-3 mb-3">
    <p>
      Technology global rating:
    </p>
    <h3>
      <%= @technology.rating %>
    </h3>
  </div>

  <div>
    <%= link_to 'back', technologies_path, class: 'btn btn-primary btn-sm mb-5' %>
  </div>

  <h3 class="mt-5 mb-5">
    <%= @technology.title %> lessons
  </h3>
</div>